server:
  port: 8888

spring:
  application:
    name: user-data-proxy
  profiles:
    active: dev

nacos:
  config:
    server-addr: ihuman-nacos:8848
    username: common-user
    password: cu123456
    type: YAML
    data-ids: dynamic-tp-nacos-demo-dev.yml,user-data-proxy-dtp-dev.yml   # 线程池配置文件必须要在此处配置
    auto-refresh: true
    group: COMMON-BIZ
    bootstrap:
      enable: true
      log-enable: true

# 开启 SpringBoot Actuator Endpoint 暴露出DynamicTp指标接口
# 开启 prometheus 指标采集端点
management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: '*'   # 测试使用，线上不要用*，按需开启