server:
  port: 8888

spring:
  application:
    name: dynamic-tp-apollo-demo
  profiles:
    active: dev

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
    httptrace:
      enabled: false
    configprops:
      enabled: false
    shutdown:
      enabled: false

apollo:
  bootstrap:
    enabled: true
    eagerLoad:
      enabled: true
    namespaces: dynamic-tp-apollo-demo-dtp.yml,application
  meta: http://81.68.181.139:8080
app:
  id: dynamic-tp-apollo-demo